# Generated by Django 2.1.1 on 2018-10-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('no', models.IntegerField(default=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('path', models.CharField(max_length=50)),
            ],
        ),
    ]
