# Generated by Django 2.1.1 on 2018-10-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
