# Generated by Django 2.1.1 on 2018-10-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app14', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='_id',
        ),
    ]
