# Generated by Django 2.1.1 on 2018-10-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
