# Generated by Django 2.1.1 on 2018-10-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=4)),
                ('fee', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='facality',
            fields=[
                ('id', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('experiance', models.DecimalField(decimal_places=1, max_digits=2)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='newclass',
            fields=[
                ('id', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
