# Generated by Django 2.1.1 on 2018-10-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app20', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculity',
            fields=[
                ('id', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('experiance', models.DecimalField(decimal_places=1, max_digits=2)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='facality',
        ),
    ]
