# Generated by Django 2.1.1 on 2018-10-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20181010_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='id',
            new_name='_id',
        ),
    ]
