# Generated by Django 2.1.1 on 2018-10-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_auto_20181010_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='_id',
            new_name='id',
        ),
    ]
