# Generated by Django 2.1.1 on 2018-10-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app12', '0002_auto_20181009_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
        ),
    ]
