# Generated by Django 2.1.1 on 2018-10-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app12', '0003_auto_20181009_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cno',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(default=4, primary_key=True, serialize=False),
        ),
    ]
